### ISSUE TITLE
Classy problem: No lensed Cl computed

### ISSUE THREAD

**Issue by miug14** [lesgourg/class_public#390]
Hello,
I am trying to run Monte Python v 3.3.0 together with CLASS v 2.9.4 using Python 3 (although I have tried using Python 2 and the error persists). I run just LCDM with no changes to class (I simply clone the code from GitHub). If I use just the Planck parameter file that comes with Monte Python, I keep getting the following error right after the chains initialise:

"File "montepython/MontePython.py", line 40, in 
sys.exit(run())
File "/home/miug14/Simulations/montepython_public/montepython/run.py", line 45, in run
sampler.run(cosmo, data, command_line)
File "/home/miug14/Simulations/montepython_public/montepython/sampler.py", line 46, in run
mcmc.chain(cosmo, data, command_line)
File "/home/miug14/Simulations/montepython_public/montepython/mcmc.py", line 787, in chain
newloglike = sampler.compute_lkl(cosmo, data)
File "/home/miug14/Simulations/montepython_public/montepython/sampler.py", line 792, in compute_lkl
value = likelihood.loglkl(cosmo, data)
File "/home/miug14/Simulations/montepython_public/montepython/likelihood_class.py", line 953, in loglkl
cl = self.get_cl(cosmo)
File "/home/miug14/Simulations/montepython_public/montepython/likelihood_class.py", line 192, in get_cl
cl = cosmo.lensed_cl(int(l_max))
File "classy.pyx", line 567, in classy.Class.lensed_cl (/home/miug14/Simulations/class/python/../python/classy.c:9149)
classy.CosmoSevereError:

Error in Class: No lensed Cl computed"

Do you have any idea where the problem might be coming from? It seems that if I try several times, the chains eventually run without a problem but the fact that I get this error so often makes me suspicious that there might be some bug. I have been trying to understand where this comes from for some months now but I just don't understand what the problem might be...
I have mentioned this problem on the Monte Python GitHub page and was told to raise the question here since the error seems to originate in classy.
Thank you!

**Comment by shan1525** [comment]
Hi everyone, 

I am facing the similar issue as @miug14  is facing. My problem is originating from the shooting algorithm.  Following is the detailed explanation of my problem along with the log file. At Montepython page it was suggested to post the problem here, as it was a CLASS error. 

#-----CLASS v2.8.2 (branch: , hash: )-----

#------Experiments to test (separated with commas)-----

data.experiments=['Planck_highl_TT', 'Planck_lowl_EE', 'Planck_lowl_TT', 'Planck_lensing']

Cosmological parameters list
data.parameters['omega_b'] = [ 2.2377, None, None, 0.015, 0.01, 'cosmo']
data.parameters['omega_cdm'] = [ 0.12010, None, None, 0.0013, 1, 'cosmo']
data.parameters['100*theta_s'] = [ 1.04110, None, None, 0.00030, 1, 'cosmo']
data.parameters['ln10^{10}A_s'] = [ 3.0447, None, None, 0.015, 1, 'cosmo']
data.parameters['n_s'] = [ 0.9659, None, None, 0.0042, 1, 'cosmo']
data.parameters['scf_parameters__1'] = [ 3.0, None, None, 0, 1, 'cosmo']
data.parameters['scf_parameters__2'] = [ 3.0, 1.0, 9.0, 0.5, 1e26, 'cosmo']
data.parameters['scf_parameters__3'] = [ 3.0, 1.0, 9.0, 0.5, 1e-26, 'cosmo']
data.parameters['scf_parameters__4'] = [ 1.0, None, None, 0, 1, 'cosmo']
data.parameters['scf_parameters__5'] = [ 2.6, 0.9, 3.0, 0.05, 1, 'cosmo']
data.parameters['scf_parameters__6'] = [ 0.0, None, None, 0, 1, 'cosmo']

Derived parameters
data.parameters['z_reio'] = [1, None, None, 0, 1, 'derived']
data.parameters['YHe'] = [1, None, None, 0, 1, 'derived']
data.parameters['H0'] = [0, None, None, 0, 1, 'derived']
data.parameters['A_s'] = [0, None, None, 0, 1e-9, 'derived']
data.parameters['sigma8'] = [0, None, None, 0, 1, 'derived']
data.parameters['log10z_c'] = [1, None, None, 0, 1, 'derived']
data.parameters['fEDE'] = [0, None, None, 0, 1, 'derived']

For Scalar Field Dynamics
data.cosmo_arguments['Omega_Lambda'] = 0
data.cosmo_arguments['Omega_fld'] = 0
data.cosmo_arguments['Omega_scf'] = -1
data.cosmo_arguments['attractor_ic_scf'] = 'no'
data.cosmo_arguments['scf_tuning_index'] = 3

#-----Likelihood-Planck_lowl_EE-----
Planck_lowl_EE.path_clik = '/home/shanno/Desktop/monte/code/plc_3.0/plc-3.01/../../../baseline/plc_3.0/low_l/simall/simall_100x143_offlike5_EE_Aplanck_B.clik'

#-----Likelihood-Planck_lowl_TT-----
Planck_lowl_TT.path_clik = '/home/shanno/Desktop/monte/code/plc_3.0/plc-3.01/../../../baseline/plc_3.0/low_l/commander/commander_dx12_v3_2_29.clik'

#-----Likelihood-Planck_lensing-----
Planck_lensing.path_clik = '/home/shanno/Desktop/monte/code/plc_3.0/plc-3.01/../../../baseline/plc_3.0/lensing/smicadx12_Dec5_ftl_mv2_ndclpp_p_teb_consext8.clik_lensing'

#-----------Cosmological-arguments---------
data.cosmo_arguments.update({'sBBN file': '/home/shanno/Desktop/monte/class_ede-master/class/bbn/sBBN.dat', 'Omega_scf': -1, 'P_k_max_h/Mpc': 1.0, 'output': 'mPk tCl lCl pCl ', 'N_ur': 2.0328, 'Omega_Lambda': 0, 'attractor_ic_scf': 'no', 'Omega_fld': 0, 'scf_tuning_index': 3, 'm_ncdm': 0.06, 'l_max_scalars': 2508, 'k_pivot': 0.05, 'lensing': ' yes ', 'non linear': 'halofit', 'N_ncdm': 1, 'T_ncdm': 0.71611})

But then it is giving the following error and montepython run is stopped:

Error in Class: background_init(L:693) :condition (pba->shooting_failed == TRUE) is true; Shooting failed, try optimising input_get_guess(). Error message:

input_init(L:436) :error in fzero_Newton(input_try_unknown_parameters, x_inout, dxdF, unknown_parameters_size, 1e-4, 1e-6, &fzw, &fevals, errmsg);
=>fzero_Newton(L:1115) :error in func(x_inout, x_size, param, F0, error_message);
=>input_try_unknown_parameters(L:3584) :error in background_init(&pr,&ba);
=>background_init(L:736) :error in background_solve(ppr,pba);
=>background_solve(L:1735) :error in generic_integrator(background_derivs, tau_start, tau_end, pvecback_integration, &bpaw, ppr->tol_background_integration, ppr->smallest_allowed_variation, &gi);
=>generic_integrator(L:112) :error in rkqs(&x, h, eps, &hdid, &hnext, derivs, parameters_and_workspace_for_derivs, pgi);
=>rkqs(L:156) :condition (xnew == *x) is true; stepsize underflow at x=4.634896e-09
Traceback (most recent call last):
File "montepython/MontePython.py", line 40, in
sys.exit(run())
File "/home/shanno/Desktop/monte/montepython_public-3.3/montepython/run.py", line 45, in run
sampler.run(cosmo, data, command_line)
File "/home/shanno/Desktop/monte/montepython_public-3.3/montepython/sampler.py", line 46, in run
mcmc.chain(cosmo, data, command_line)
File "/home/shanno/Desktop/monte/montepython_public-3.3/montepython/mcmc.py", line 787, in chain
newloglike = sampler.compute_lkl(cosmo, data)
File "/home/shanno/Desktop/monte/montepython_public-3.3/montepython/sampler.py", line 776, in compute_lkl
value = likelihood.loglkl(cosmo, data)
File "/home/shanno/Desktop/monte/montepython_public-3.3/montepython/likelihood_class.py", line 953, in loglkl
cl = self.get_cl(cosmo)
File "/home/shanno/Desktop/monte/montepython_public-3.3/montepython/likelihood_class.py", line 192, in get_cl
cl = cosmo.lensed_cl(int(l_max))
File "classy.pyx", line 567, in classy.Class.lensed_cl
classy.CosmoSevereError:

Error in Class: No lensed Cl computed.....

So, If anyone has any suggestion please share. It will be very useful for us.

Best,
shan.

**Comment by shan1525** [comment]
Hi @miug14 ,

My LCDM  param is running fine . Can you share your log file here so that I can understand your problem well. I ran the LCDM with python2.7. It didn't give any error. Please share so that I can give some suggestions.  My problem is coming when I try to run a quintessence type model. 

Best, 
shan.

**Comment by ThomasTram** [comment]
Hi

This sounds weird. The problem is that MontePython is calling `cosmo.lensed_cl(int(l_max))` in a situation where the cosmo.compute(['lensing']) call failed. This raises a `classy.CosmoSevereError` which stops MontePython. the  But this should not happen, since MontePython is supposed to catch this error before.

Specifically, this happens in line L724--L764 in sampler.py. First try to see if fall through the try-except without returning even though CLASS prints an error message. If that is the case, try to see if and why classy fails to raise the `CosmoComputationError` exception in this line:
https://github.com/lesgourg/class_public/blob/2dd9238f65ef14a02a7553716eb9c7581bc1c511/python/classy.pyx#L426

Also, try to see if the same thing happens with e.g. the 2.8 branch of CLASS.

Cheers,
Thomas

**Comment by miug14** [comment]
Hi,
Thank you for your message. I have checked now and everything runs fine just for LCDM, I was using the modified file instead. I too also have a scf modification in order to simulate interacting dark energy. This week I tried doing the same changes for version 2.8 and the error persists. What I find strange is that, if I launch (let's say) 10 chains, then maybe 1 will run without a problem and the others will return this error right at the beginning...

**Comment by miug14** [comment]
I have not modified the lensing.c file, just the input.c, background.c and perturbations.c, maybe there were modifications that had to be done to the lensing file?

**Comment by shan1525** [comment]
Thank you so much @ThomasTram  for looking into this problem. I really appreciate your help. I will follow your suggestions and see whether the problem still persists or not.  I will report the outcome here as soon as I follow your suggestions. Let's hope it resolves the issue. Thanks again for your help.

**Comment by shan1525** [comment]
Hi @miug14  you also have to add your parameters in corresponding  .h files in the include directory. Also add your new parameter in classy.pyx  file. I would recommend you from my experience that after compiling your CLASS don't run the Montepython directly. First check your initialisation in the python module of the CLASS as the following:

params = {
"h": 0.6774,
"omega_b": 0.02230,
"Omega_cdm": 0.2603,
"Omega_fld" : 0,
"background_verbose" : 1, 
"output" : "tCl,mPk" 
}  
from classy import Class
cosmos = Class() 
cosmos.set(params) 
cosmos.compute().  It is for LCDM, make your ini like this. If it runs in CLASS, that means you are good for running it in Montepython.

Now ,  For the scalar field models . I would suggest you to look into Vivian code . There, he has implemented an Axion like scalar field. You will get some idea for adding your parameter in CLASS. Here is the link for that code :  https://github.com/PoulinV/AxiCLASS


Best,
shan.

**Comment by miug14** [comment]
Thank you very much for your comments @shan1525 and @ThomasTram! I will have a look and if I figure out where the problem is coming from I will let you know. I can run the same modification on v2.7 without a problem, it only arises when I try to use v2.8 and v2.9. I can run the model fine on CLASS, the problem only arises when interfacing with Monte Python, which makes sense according to your comment on classy.pyx. Also, thank you for referring back to Vivian's code, that is very helpful!
Cheers!

**Comment by nkhadka21** [comment]
Hi all,
Did anyone solve this issue? I also got this problem. It would be great if anyone one could suggest a solution.

Thank you,

Narayan
