### ISSUE TITLE
Isuue in importing Python Wrapper (CLASS)

### ISSUE THREAD

**Issue by saadkamranok** [lesgourg/class_public#469]
i am trying to use CLASS python wrapper for Monte python but when i try to import it, shows this error. i am using ubuntu 18 operating system and python 2.7 from anaconda2. 

>>> from classy import Class
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /home/saad/.local/lib/python2.7/site-packages/classy.so: undefined symbol: _ZGVbN2v_sin

don't know what to do

**Comment by ShazAlvi** [comment]
Most likely there is a mixup of the python version i.e. you have compiled it with a different version of python and it's being called inside an environment based on a different python.

**Comment by saadkamranok** [comment]
> Most likely there is a mixup of the python version i.e. you have compiled it with a different version of python and it's being called inside an environment based on a different python. I would first make sure that the two python versions are the same.

@ShazAlvi thanks for your response but when i type python --version it shows me the one with anaconda like this.

~$ python
Python 2.7.13 |Anaconda 4.4.0 (64-bit)| (default, Dec 20 2016, 23:09:15) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> from classy import Class
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /home/saad/.local/lib/python2.7/site-packages/classy.so: undefined symbol: _ZGVbN2v_sin

is there something i am missing ?

**Comment by saadkamranok** [comment]
Import problem is solved. i was using 2.6 version of class. now i install 3.1.1 (latest) and it is working . Thanks
