### ISSUE TITLE
Is the current version Python3 compatible? 

### ISSUE THREAD

**Issue by evanbiederstedt** [lesgourg/class_public#77]
I've tried installing the Python wrapper following this link: https://github.com/lesgourg/class_public/wiki/Python-wrapper

Using Python3.4, I install with 

`python3 setup.py install --user`

This outputs the following TypeError:

```
34 warnings generated.
Traceback (most recent call last):
  File "setup.py", line 36, in <module>
    data_files=(('bbn', ['../bbn/sBBN.dat']),)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/command/install.py", line 539, in run
    self.run_command('build')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/command/build.py", line 126, in run
    self.run_command(cmd_name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Cython/Distutils/build_ext.py", line 164, in run
    _build_ext.build_ext.run(self)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/Cython/Distutils/build_ext.py", line 172, in build_extensions
    self.build_extension(ext)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/command/build_ext.py", line 535, in build_extension
    target_lang=language)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/ccompiler.py", line 717, in link_shared_object
    extra_preargs, extra_postargs, build_temp, target_lang)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/unixccompiler.py", line 157, in link
    libraries)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/ccompiler.py", line 1089, in gen_lib_options
    lib_opts.append(compiler.library_dir_option(dir))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/unixccompiler.py", line 205, in library_dir_option
    return "-L" + dir
TypeError: Can't convert 'bytes' object to str implicitly
```

**Comment by ThomasTram** [comment]
No, you should use Python 2.7.

Cheers,
Thomas

**Comment by evanbiederstedt** [comment]
Thanks. Are there any short-term plans to make it Python 3.x compatible? How much of the code would need to be revised? (There are good reasons I need to use Python 3.x and Python 2.7 won't work.)

Just checking. Thanks, Evan

**Comment by ThomasTram** [comment]
No plans, but you are welcome to do it yourself of course! Since Cython is Python3 compatible, the only changes needed should be in the setup.py script, classy.pyx and cclassy.pxd perhaps. However, I have no idea what the needed changes are..

**Comment by evanbiederstedt** [comment]
"the only changes needed should be in the setup.py script, classy.pyx and cclassy.pxd perhaps"

That's exactly what I needed to know. There shouldn't be many changes; if I do this, I'll hand you the sourcecode via GitHub. 

Thanks. Feel free to close this issue.

**Comment by ThomasTram** [comment]
Thanks, I am sure that would be useful to some users!
